### ISSUE TITLE
Installation on Debian 9

### ISSUE THREAD

**Issue by LEONIDAS-0117** [qunxyz/plasma-applet-caffeine-plus#5]
After commenting the lines 341 to 353 in the file plugin/caffeine-plus.cpp i could complete the installation successfully.
The plugin is fully functional even without them.

**Comment by qunxyz** [comment]
well, you got the point. actually I can't find a better way to make this plugin working for all apps. these lines will be improved if I got any better idea. If you got one, tell me or you can make a pr. thanks for your reporting
