### ISSUE TITLE
Widget not included in System Tray

### ISSUE THREAD

**Issue by alexgallotta** [qunxyz/plasma-applet-caffeine-plus#7]
I added the widget on a Panel, but unlike other widgets (like redshift) it is not included in the list I can see in System Tray, and thus showing only when active.

**Comment by qunxyz** [comment]
sorry for replying you after so so long, I will check that in the next few days. if you can provide more info, that would be nice.

**Comment by alexgallotta** [comment]
Plasma versions have changed and I am not using caffeine anymore since it looks like plasma is not putting screensaver while playing videos (the reason why I added caffeine in the first place).
Thanks anyway

**Comment by i-need-to-tell-you-something** [comment]
When right-clicking Plasma system tray and choosing "System Tray Settings",
![image](https://user-images.githubusercontent.com/9165395/61390219-05265c80-a8c3-11e9-981d-680d447046f9.png)

Caffeine Plus is not one of the options when looking at the list of "Extra Items" in the "General" tab. It does show Redshift Control there as well as two weather widgets I have installed. 
![image](https://user-images.githubusercontent.com/9165395/61389848-4702d300-a8c2-11e9-88e1-04f4b5027957.png)

Some other random applications I have (e.g. Jami, Joplin, Gnome-Pie, Nextcloud) have a tray icon some other way (not in the Plasma tray Extra Items list either).

Caffeine Plus not being among the tray icons is a bigger problem with a multi-row tray. Like this example vertical bar:
![image](https://user-images.githubusercontent.com/9165395/61389897-6437a180-a8c2-11e9-80e1-27a1853eabf4.png)

**Comment by qunxyz** [comment]
Thank you for your reporting. I'll look into it. This month I would released a new version, it might be fixed by that time.

**Comment by properlypurple** [comment]
I added a pull request to fix this. I hope @qunxyz will merge this and make a release :)

**Comment by kupiqu** [comment]
> I added a pull request to fix this. I hope @qunxyz will merge this and make a release :)

Hmm, I cannot achieve showing the applet in the systray even with that change, I wonder why
