### ISSUE TITLE
Caffeine always active with Latte Dock

### ISSUE THREAD

**Issue by t14462** [qunxyz/plasma-applet-caffeine-plus#9]
Latte Dock works like a fullscreen application, or something.
So please add exclusion for Latte

**Comment by qunxyz** [comment]
thank you for your report. I will look into it in the next few days. if you can provide more info, like system info, plasma version, etc, that would be very helpful.

**Comment by t14462** [comment]
Antergos (binary Arch distro), KDE 5.15.4, Frameworks 5.56.0, Qt 5.12.2

Xorg and other things newest (from Arch repo) too.

**Comment by qunxyz** [comment]
hi, I checked. but seems no problem. I added debug function, so it can collect some info during runtime. try new version, log file will be placed "{yourhomedir}/caffeine-plugs-debug.log". you can enable debug in   Advanced panel.

**Comment by t14462** [comment]
Hmm... it is strange. Now it works for me good to.

Maybe latte was misconfigurated, or bug in frameworks

**Comment by qunxyz** [comment]
glad to hear that. I close this issue now. if you met this issue again, please open a new one. thank you.
